baseURL: "https://dcebotarenco.github.io/"
relativeURLs: true
languageCode: en-us
title: bugdone.io
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files
params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/blue-long-logo.png
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Empower. Deploy.
    # Hero subtitle (optional)
    subtitle: Professional software development team 
    # Button text
    buttontext: Get in touch
    # Where the main hero button links to
    buttonlink: "#contact"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    # clientlogos:
    # - tremend_owler_20180213_184451_original.png
    # - tribe.svg
    # - kromo.svg
    # - infinite.svg
    # - gutwork.svg
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  # - title: Features
    # url: /
  # - title: Pricing
    # url: /
  - title: Portfolio
    # sublinks:
    # - title: Dropdown item
    #   url: /
    # - title: Dropdown item
    #   url: /
    # - title: Dropdown item
    #   url: /
  # - title: Log in
    # url: /
  # - title: Sign up
    # url: /
    # button: true
  # sidebar:
    # Logo (from /images/logos/___.svg)
    # logo: fresh-square
    # sections:
    # - title: User
    #   icon: user
    #   links:
    #   - text: Profile
    #     url: /
    #   - text: Account
    #     url: /
    #   - text: Settings
    #     url: /
    # - title: Messages
    #   icon: envelope
    #   links:
    #   - text: Inbox
    #     url: /
    #   - text: Compose
    #     url: /
    # - title: Images
    #   icon: image
    #   links:
    #   - text: Library
    #     url: /
    #   - text: Upload
    #     url: /
    # - title: Settings
    #   icon: cog
    #   links:
    #   - text: User settings
    #     url: /
    #   - text: App settings
    #     url: /
  section1:
    title: Great power comes
    subtitle: with great responsibility
    tiles:
    - title: Software development
      icon: mouse-globe
      text: Build reliable and scalable applications
      url: /#contact
      buttonText: Get started
    - title: Cloud integration
      icon: laptop-cloud
      text: Integrate with leading cloud providers
      url: /#contact
      buttonText: Get started
    - title: Maintenance
      icon: plug-cloud
      text: This is some explanatory text that is on two rows
      url: /#contact
      buttonText: Get started
  # section2:
  #   title: You're here because you want the best
  #   subtitle: And we know it
  #   features:
  #   - title: Global remote team
  #     text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #     # Icon (from /images/illustrations/icons/___.svg)
  #     icon: laptop-globe
  #   - title: Cross-device synchronisation
  #     text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #     icon: doc-sync
  #   - title: Nomad system
  #     text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #     icon: mobile-feed
  section3:
    title: One software company
    subtitle: To rule them all
    image: illustrations/views/slider-3.jpg
    buttonText: Get in contact
    buttonLink: "#contact"
  section4:
    title: Our Clients love us!
    subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    clients:
    - name: Irma Walters
      quote: An excellent feedback that is missing. Drop it
      job: Accountant
      img: 1
    - name: John Bradley
      quote: Fabulous message from yet unknown client
      job: Financial Analyst
      img: 2
    - name: Gary Blackman
      quote: He is still thinking..
      job: HR Manager
      img: 3
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: blue-short-logo.png
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/#
      # Icons are from Font Awesome
      icon: github
    - link: https://dribbble.com/#
      icon: dribbble
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/#
      icon: twitter
    - link: https://bitbucket.org/#
      icon: bitbucket
    bulmalogo: true
    quicklinks:
      column1:
        title: "About"
        links:
        - text: Discover features
          link: /
        - text: Why choose our company?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: AGB
          link: /agb
      column2:
        title: "Privacy"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second
